line-length = 120

[lint]
select = ["I", "F401"]
ignore = []
pydocstyle.convention = "google"
fixable = ["ALL"]

[lint.per-file-ignores]
"tests/*/**" = ["D"]
"scripts/**" = ["D"]

[format]
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"