dev_namespaces:
  users:
    pascal@everycure.org: dev-pascal
    piotr@everycure.org: dev-piotr
    mateusz@everycure.org: dev-mateusz
    laurens@everycure.org: dev-laurens
    ahuebschen@scripps.edu: dev-alan
  
    # Data Minded folks
    emil.krause@dataminded.com: dev-emil
    siyan.luo@dataminded.com: dev-siyan
    oliver.willekens@dataminded.com: dev-oliver
  
    Pascal.Brokmeier@gmail.com: dev-pascal-test
  
argo:
  namespace: argo-workflows
  rbac:
    users:
      # add new people here that should be able to submit workflows
    groups:
      - matrix-all@everycure.org
      - data-science@everycure.org
      - ext.subcontractors@everycure.org
      - data-science@everycure.org
      - ext.subcontractors.standard@everycure.org
      - ext.subcontractors.embiology@everycure.org