repos:
  # Code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        exclude: | 
          (?x)^(
            pipelines/matrix/packages|
            services/synonymizer/api/modules/synonymize
          )
      # Run the formatter.
      - id: ruff-format
        exclude: |
          (?x)^(
            pipelines/matrix/packages|
            docs/src/
          )
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        exclude: | 
          (?x)^(
            pipelines/matrix/packages|services/|
            docs/src/experiments/ |
            docs/src/onboarding/ |
            services/synonymizer/api/modules/synonymize
          )
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
    -   id: debug-statements
    -   id: check-merge-conflict
    # -   id: check-yaml

  # checks github actions files for errors
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.26 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terragrunt-hclfmt