apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: prometheus-health-check
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 9090
        requestPath: /healthz
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: prometheus-operated
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-health-check
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3000
        requestPath: /api/health
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: kube-prometheus-stack-grafana