apiVersion: v2
name: kube-prometheus-stack
description: Prometheus and Grafana deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: kube-prometheus-stack
  version: 78.2.1
  repository: https://prometheus-community.github.io/helm-charts